import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY is not configured");

    const body = await req.json();
    const {
      vehicleRegistration,
      saleDate,
      salePrice,
      distanceSale,
      warrantyProvided,
      financeInvolved,
      mileageAtSale,
      complaintType,
      customerComplaintText,
      daysSinceSale,
      currentMileage,
      mileageSinceSale,
      vehicleDrivable,
      repairAttempted,
      legalTimeline,
      evidence,
    } = body;

    const evidenceList = [
      evidence.signedPdiAvailable && "Signed PDI is available",
      evidence.distanceSalePackCompleted && "Distance Sale Pack has been completed",
      evidence.provenanceReportProvided && "Provenance report was provided",
      evidence.serviceHistoryDisclosed && "Service history was disclosed to the customer",
      evidence.faultInspectionReportAvailable && "Fault inspection report is available",
      evidence.independentInspectionRequested && "Independent inspection has been requested",
      evidence.customerRefusedInspection && "Customer has refused inspection",
    ]
      .filter(Boolean)
      .join("; ");

    const systemPrompt = `You are a professional automotive compliance advisor specialising in UK consumer law. 
You generate structured, calm, legally compliant dispute response templates for UK used car dealers.

CRITICAL RULES:
- Never generate aggressive, dismissive or unlawful responses
- Never include blanket "no refund" language
- Never deny valid consumer rights
- Always reference the correct legal position based on the timeline provided
- Tone must be: professional, neutral, calm, legally aligned, protective but not confrontational
- Do NOT mention AI, do NOT mention that this was generated by software
- Write as if the dealer themselves is responding professionally
- Use plain English that is clear to a layperson but legally structured

LEGAL FRAMEWORK:
- Consumer Rights Act 2015 (CRA 2015)
- Consumer Contracts Regulations 2013
- FCA principles (if finance involved)

OUTPUT FORMAT: You MUST return valid JSON with exactly this structure:
{
  "emailResponse": "Full structured email response (professional, 300-500 words)",
  "smsVersion": "Short SMS version (max 160 chars)",
  "internalSummary": "Internal case summary for audit (bullet points, ~150 words)",
  "riskLevel": "low" | "moderate" | "high",
  "suggestedNextSteps": ["step 1", "step 2", "step 3", "step 4"]
}

RISK LEVEL GUIDANCE:
- low: cosmetic, over 6 months, strong documentation, vehicle drivable
- moderate: mechanical/electrical, 30-180 days, some documentation gaps
- high: rejection claim under 30 days, finance involved, minimal documentation, customer refused inspection`;

    const userPrompt = `Generate a dispute response for the following case:

VEHICLE: ${vehicleRegistration || "Not specified"} | Sale Price: £${salePrice || "N/A"} | Mileage at Sale: ${mileageAtSale || "N/A"}
SALE DATE: ${saleDate || "N/A"} | Days Since Sale: ${daysSinceSale}
DISTANCE SALE: ${distanceSale ? "Yes" : "No"} | WARRANTY PROVIDED: ${warrantyProvided ? "Yes" : "No"} | FINANCE INVOLVED: ${financeInvolved ? "Yes" : "No"}

COMPLAINT TYPE: ${complaintType.replace(/-/g, " ").toUpperCase()}
CUSTOMER'S COMPLAINT: "${customerComplaintText || "Not provided"}"

USAGE SINCE SALE: ${mileageSinceSale} miles | Current Mileage: ${currentMileage || "N/A"}
VEHICLE DRIVABLE: ${vehicleDrivable === true ? "Yes" : vehicleDrivable === false ? "No" : "Unknown"}
REPAIR ATTEMPTED: ${repairAttempted === true ? "Yes" : repairAttempted === false ? "No" : "Unknown"}

LEGAL TIMELINE: ${legalTimeline === "under-30" ? "Under 30 days (Short-term right to reject period)" : legalTimeline === "30-to-6-months" ? "30 days to 6 months (dealer right to repair/replace)" : "Over 6 months (burden of proof shifts to consumer)"}

EVIDENCE AVAILABLE: ${evidenceList || "None recorded"}

Apply the correct legal posture based on the timeline. The email response must:
1. Acknowledge the customer's contact professionally
2. Reference the correct legal rights for this timeline
3. Propose a structured inspection/resolution process
4. Remain calm and professional throughout
5. Include a clear next step for the customer`;

    const response = await fetch(
      "https://ai.gateway.lovable.dev/v1/chat/completions",
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${LOVABLE_API_KEY}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "google/gemini-3-flash-preview",
          messages: [
            { role: "system", content: systemPrompt },
            { role: "user", content: userPrompt },
          ],
          response_format: { type: "json_object" },
        }),
      }
    );

    if (!response.ok) {
      if (response.status === 429) {
        return new Response(
          JSON.stringify({ error: "Rate limit exceeded. Please try again in a moment." }),
          { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      if (response.status === 402) {
        return new Response(
          JSON.stringify({ error: "AI usage credits required. Please add credits to your workspace." }),
          { status: 402, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      const errText = await response.text();
      console.error("AI gateway error:", response.status, errText);
      return new Response(
        JSON.stringify({ error: "AI generation failed. Please try again." }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const aiData = await response.json();
    const content = aiData.choices?.[0]?.message?.content;
    if (!content) throw new Error("Empty response from AI");

    const parsed = JSON.parse(content);

    return new Response(JSON.stringify(parsed), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (err) {
    console.error("dispute-response error:", err);
    return new Response(
      JSON.stringify({ error: err instanceof Error ? err.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
